import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Image 
          className={styles.landingImage}
          src="/assets/home/background-home-desktop.jpg"
          alt="desktop image"
          layout="fill"
          objectFit="cover"
          objectPosition="center"
        /> */}
        <div className={styles.home_text}>
          <div className={styles.main_text}>
            <div className={styles.uppercase_text}>
              <h5>So, you want to travel to</h5>
              <h1>Space</h1>
            </div>
            <p>
              Let’s face it; if you want to go to space, you might as well
              genuinely go to outer space and not hover kind of on the edge of
              it. Well sit back, and relax because we’ll give you a truly out of
              this world experience!
            </p>
          </div>
          <div className={styles.explore_button}>
            <button className={styles.button}>Explore</button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
